### ISSUE TITLE
What is ECC Priv key?

### ISSUE THREAD

**Issue by enzifiri** [permadao/Permaswap#4]
ECC Priv Key, what does that mean? 
![image](https://github.com/permadao/Permaswap/assets/76253089/98ddf597-7e4a-4adc-860d-733f3711b279)

**Comment by xiaojay** [comment]
ECC private key is a ethereum account private key. When you run a Router, it is used to sign router tx which is posted to everpay / arweave. When your run a HALO Node, it is not used, just filled a test account private key.

**Comment by enzifiri** [comment]
I see, this is the first time I've seen it specified as ECC. I suggest correcting it to "EVM Private Key".

**Comment by xiaojay** [comment]
cool, changed
